name: enchanted_regex
description: A package that enhances dart regex api. Mainly when working with named group's.
version: 1.0.5
repository: https://github.com/igormidev/enchanted_regex
issue_tracker: https://github.com/igormidev/enchanted_regex/issues

dependencies:
  enchanted_collection: '>=1.0.0 <2.0.0'

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

screenshots:
  - description: The logo of the package.
    path: art/logo.PNG

topics:
  - regex
  - utils